### ISSUE TITLE
Error Connecting to Gen5 DVR

### ISSUE THREAD

**Issue by joshn-ridewta-com** [whatcomtrans/nodeOnPiOnABus#19]
Error: connect ECONNREFUSED 192.168.1.129:5070
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

**Comment by joshn-ridewta-com** [comment]
Not sure if this is a Pi or DVR issue.
